[tool.ruff]
line-length = 120
target-version = 'py310'

[tool.poetry]
name = "consultation-analyser"
version = "0.1.0"
description = ""
authors = ["i.AI <i-dot-ai-enquiries@cabinetoffice.gov.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.2"
django-environ = "^0.11.2"
psycopg = "^3.1.18"


[tool.poetry.group.development.dependencies]
ruff = "^0.2.2"
pre-commit = "^3.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
