name: Check migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.12

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pguser
          POSTGRES_PASSWORD: pgpass
          POSTGRES_DB: consultations_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install poetry & deps
        run: |
          python -m pip install --upgrade poetry
          poetry install --with development

      # - name: Get test env vars
      #   uses: c-py/action-dotenv-to-setenv@v5
      #   with:
      #     env-file: .env.test

      - name: Check migrations
        run: |
          poetry run python manage.py migrate
          poetry run python manage.py makemigrations --check
        env:
          DJANGO_SECRET_KEY: dummy-key
          DATABASE_URL: psql://consultations_test:@localhost:5432/consultations_test



