name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: install poetry & deps
        run: |
          python -m pip install --upgrade poetry
          poetry install --with development

      - name: pytest
        run: poetry run pytest
